### ISSUE TITLE
Switch default pip install arguments for test job

### ISSUE THREAD

**Issue by apeschel** [CircleCI-Public/python-orb#49]
## Describe Request:

A discussion in the Python Packaging Sample Project suggests `requirements.txt` should not be used for testing. Instead, the best practice recommended there is to install the module before running the testing.

It seems like there are a couple of reason this is recommended:
* It works when the modules are in a subdirectory (like src)
* requirements.txt is intended for development, not for release, and so is better to use the requirements listed in `setup.py`, since that is what will be included with what is actually distributed.

In effect, this would switch the defaults to run `pip install -e .` instead of `pip install -r requirements.txt`

## Supporting Documentation Links:

Here's a link to the discussion: https://github.com/pypa/sampleproject/issues/129

**Comment by dsayling** [comment]
I agree this is another way to set up an environment for testing, but for reproducing a developer environment (where a developer would still run tests), this is still rather common as well to just stick with `requirements.txt`. 

The reason for using the `requirements.txt` is to use it as a 'checksum' for the cache. If we were to use the `setup.py`, any change to the file itself would result in gathering all the dependencies any time the `setup.py` changes (like an author change or license change). Now, you're also faced with a more serious problem. If your application changes, but your `setup.py` does not change, you will in fact restore an old version of the application from the cache that does not contain your latest update because the `pip install -e .` did not run. Hypothetically now, if you were to update your `setup.py` every changeset, you would then install all your dependencies from scratch every time, but then you'd remove the value of the command, which is storing the cache.

I suggest still using `requirements.txt` to install your dependencies and then install your application if you want the caching from the python environment. [Here in my own sample app](https://github.com/dsayling/ssfa/blob/master/.circleci/config.yml), you can see how I use the orb command twice with two separate caches, the test env, and the app env, and then install the app itself for testing.

**Comment by apeschel** [comment]
@dsayling Thanks for the feedback!

I noticed in your sample app, you're manually running the tests, rather than using the `python/test` job included in the orb, and you're using `pip install -e .` as  I mentioned.

```
      - run:
          name: Install package as app
          command: |
            pip install -e .
      - run:
          name: Start Flask app in background
          command: |
            cd app
            python app.py
          background: true
      - run:
          name: Run tests
          command: |
            cd tests
            python -m unittest
```

I'm not clear on why you're starting flask, since you should be able to run the unittests without starting the flask app. In theory, you should be able to do this instead:

```
      - python/test:
          args: '-e .'
```

Much simpler, no?

But it's still problematic, because this actually runs `pip install -r requirements.txt -e .` rather than just `pip install -e .`

I think the problem is the `install-packages` command was written with develop in mind, and when it came time to install packages for testing, the logic was never added to handle the different package install workflow for testing.

Here's the pip install-package logic: https://github.com/CircleCI-Public/python-orb/blob/3c5e34de69a3276d9a4af738133d17398994ec1b/src/commands/install-packages.yml#L105-L113

I think what would make sense it to have separate `pip-devel` and `pip-dist` targets. Change the linked code to `pip-devel`, and make `pip-dist` look like this:

```
  - when:
      condition:
        equal: [pip-dist, << parameters.pkg-manager >>]
      steps:
        - run:
            name: "Install dependencies with pip using project setup.py"
            working_directory: <<parameters.app-dir>>
            command: |
              pip install -e . << parameters.args >>
```

You're right that the cache would need to be switched to use `setup.py`, which has more metadata than `requirements.txt`, but I personally don't change that file very often, so it wouldn't make much of a difference for caching purposes. I'm curious what workflow you are thinking of that would require `setup.py` to change on every commit.

**Comment by dsayling** [comment]
I should indeed be starting flask in the unittest yourself, you are correct! This is honestly due to laziness on my own part and just never got it going. 

A workflow I have seen around updating the `setup.py` is using some sort of hook to update the version field if not reading from a version file. And updating the version to include a hash or something for the changeset. 

I think your proposed enum to the pkg-manager argument is a great idea. I think the best think to simply do though is to just run the command again and just assume the cache to the requirements.txt (I assume you have one still?) and always make sure the `pip install -e .` runs. 

I'll work on an update.

**Comment by dsayling** [comment]
In the change above #48, you can still use the requirements.txt as the checksum, or you can use the setup.py. This is the test I just added to this project's config.

```
    jobs:
    ....
      - python/test:
          name: job-test-pip-dist
          pkg-manager: pip-dist
          app-dir: ~/project/sample_pip
          pip-dependency-file: setup.py
```

**Comment by apeschel** [comment]
@dsayling Thanks for your help on this, I like your solution!
